/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as Setup2faRouteImport } from './routes/setup-2fa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthVitalsRouteImport } from './routes/_auth/vitals'
import { Route as AuthNewsRouteImport } from './routes/_auth/news'
import { Route as AuthKanbanRouteImport } from './routes/_auth/kanban'
import { Route as AuthHealthHelpRouteImport } from './routes/_auth/health-help'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthCompanionRouteImport } from './routes/_auth/companion'
import { Route as AuthAiAssistantRouteImport } from './routes/_auth/ai-assistant'
import { Route as AuthSessionsIndexRouteImport } from './routes/_auth/sessions.index'
import { Route as AuthSessionsNewRouteImport } from './routes/_auth/sessions/new'
import { Route as AuthSessionsSessionIdRouteImport } from './routes/_auth/sessions/$sessionId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const Setup2faRoute = Setup2faRouteImport.update({
  id: '/setup-2fa',
  path: '/setup-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVitalsRoute = AuthVitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNewsRoute = AuthNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthRoute,
} as any)
const AuthKanbanRoute = AuthKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHealthHelpRoute = AuthHealthHelpRouteImport.update({
  id: '/health-help',
  path: '/health-help',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompanionRoute = AuthCompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAiAssistantRoute = AuthAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSessionsIndexRoute = AuthSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSessionsNewRoute = AuthSessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSessionsSessionIdRoute = AuthSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/setup-2fa': typeof Setup2faRoute
  '/sign-up': typeof SignUpRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/ai-assistant': typeof AuthAiAssistantRoute
  '/companion': typeof AuthCompanionRoute
  '/dashboard': typeof AuthDashboardRoute
  '/health-help': typeof AuthHealthHelpRoute
  '/kanban': typeof AuthKanbanRoute
  '/news': typeof AuthNewsRoute
  '/vitals': typeof AuthVitalsRoute
  '/sessions/$sessionId': typeof AuthSessionsSessionIdRoute
  '/sessions/new': typeof AuthSessionsNewRoute
  '/sessions/': typeof AuthSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup-2fa': typeof Setup2faRoute
  '/sign-up': typeof SignUpRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/ai-assistant': typeof AuthAiAssistantRoute
  '/companion': typeof AuthCompanionRoute
  '/dashboard': typeof AuthDashboardRoute
  '/health-help': typeof AuthHealthHelpRoute
  '/kanban': typeof AuthKanbanRoute
  '/news': typeof AuthNewsRoute
  '/vitals': typeof AuthVitalsRoute
  '/': typeof AuthIndexRoute
  '/sessions/$sessionId': typeof AuthSessionsSessionIdRoute
  '/sessions/new': typeof AuthSessionsNewRoute
  '/sessions': typeof AuthSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/setup-2fa': typeof Setup2faRoute
  '/sign-up': typeof SignUpRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_auth/ai-assistant': typeof AuthAiAssistantRoute
  '/_auth/companion': typeof AuthCompanionRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/health-help': typeof AuthHealthHelpRoute
  '/_auth/kanban': typeof AuthKanbanRoute
  '/_auth/news': typeof AuthNewsRoute
  '/_auth/vitals': typeof AuthVitalsRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/sessions/$sessionId': typeof AuthSessionsSessionIdRoute
  '/_auth/sessions/new': typeof AuthSessionsNewRoute
  '/_auth/sessions/': typeof AuthSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup-2fa'
    | '/sign-up'
    | '/two-factor'
    | '/verify-email'
    | '/ai-assistant'
    | '/companion'
    | '/dashboard'
    | '/health-help'
    | '/kanban'
    | '/news'
    | '/vitals'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup-2fa'
    | '/sign-up'
    | '/two-factor'
    | '/verify-email'
    | '/ai-assistant'
    | '/companion'
    | '/dashboard'
    | '/health-help'
    | '/kanban'
    | '/news'
    | '/vitals'
    | '/'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/sessions'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/setup-2fa'
    | '/sign-up'
    | '/two-factor'
    | '/verify-email'
    | '/_auth/ai-assistant'
    | '/_auth/companion'
    | '/_auth/dashboard'
    | '/_auth/health-help'
    | '/_auth/kanban'
    | '/_auth/news'
    | '/_auth/vitals'
    | '/_auth/'
    | '/_auth/sessions/$sessionId'
    | '/_auth/sessions/new'
    | '/_auth/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  Setup2faRoute: typeof Setup2faRoute
  SignUpRoute: typeof SignUpRoute
  TwoFactorRoute: typeof TwoFactorRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-2fa': {
      id: '/setup-2fa'
      path: '/setup-2fa'
      fullPath: '/setup-2fa'
      preLoaderRoute: typeof Setup2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/vitals': {
      id: '/_auth/vitals'
      path: '/vitals'
      fullPath: '/vitals'
      preLoaderRoute: typeof AuthVitalsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/news': {
      id: '/_auth/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthNewsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/kanban': {
      id: '/_auth/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthKanbanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/health-help': {
      id: '/_auth/health-help'
      path: '/health-help'
      fullPath: '/health-help'
      preLoaderRoute: typeof AuthHealthHelpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/companion': {
      id: '/_auth/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof AuthCompanionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ai-assistant': {
      id: '/_auth/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthAiAssistantRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sessions/': {
      id: '/_auth/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthSessionsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sessions/new': {
      id: '/_auth/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof AuthSessionsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sessions/$sessionId': {
      id: '/_auth/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthSessionsSessionIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAiAssistantRoute: typeof AuthAiAssistantRoute
  AuthCompanionRoute: typeof AuthCompanionRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthHealthHelpRoute: typeof AuthHealthHelpRoute
  AuthKanbanRoute: typeof AuthKanbanRoute
  AuthNewsRoute: typeof AuthNewsRoute
  AuthVitalsRoute: typeof AuthVitalsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthSessionsSessionIdRoute: typeof AuthSessionsSessionIdRoute
  AuthSessionsNewRoute: typeof AuthSessionsNewRoute
  AuthSessionsIndexRoute: typeof AuthSessionsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAiAssistantRoute: AuthAiAssistantRoute,
  AuthCompanionRoute: AuthCompanionRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthHealthHelpRoute: AuthHealthHelpRoute,
  AuthKanbanRoute: AuthKanbanRoute,
  AuthNewsRoute: AuthNewsRoute,
  AuthVitalsRoute: AuthVitalsRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthSessionsSessionIdRoute: AuthSessionsSessionIdRoute,
  AuthSessionsNewRoute: AuthSessionsNewRoute,
  AuthSessionsIndexRoute: AuthSessionsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  Setup2faRoute: Setup2faRoute,
  SignUpRoute: SignUpRoute,
  TwoFactorRoute: TwoFactorRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
