/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as Setup2faRouteImport } from './routes/setup-2fa'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthVitalsRouteImport } from './routes/_auth/vitals'
import { Route as AuthTrainBodyRouteImport } from './routes/_auth/train-body'
import { Route as AuthTestAiRouteImport } from './routes/_auth/test-ai'
import { Route as AuthSymptomsRouteImport } from './routes/_auth/symptoms'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthPharmacistRouteImport } from './routes/_auth/pharmacist'
import { Route as AuthNewsRouteImport } from './routes/_auth/news'
import { Route as AuthMedicationsRouteImport } from './routes/_auth/medications'
import { Route as AuthKanbanRouteImport } from './routes/_auth/kanban'
import { Route as AuthHealthHelpRouteImport } from './routes/_auth/health-help'
import { Route as AuthFriendChatRouteImport } from './routes/_auth/friend-chat'
import { Route as AuthErAlertsRouteImport } from './routes/_auth/er-alerts'
import { Route as AuthDrugInfoRouteImport } from './routes/_auth/drug-info'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthCompanionRouteImport } from './routes/_auth/companion'
import { Route as AuthAllergiesRouteImport } from './routes/_auth/allergies'
import { Route as AuthAiAssistantRouteImport } from './routes/_auth/ai-assistant'
import { Route as AuthAdminPanelRouteImport } from './routes/_auth/admin-panel'
import { Route as AuthAdminBreachesRouteImport } from './routes/_auth/admin-breaches'
import { Route as AuthAdminApprovalsRouteImport } from './routes/_auth/admin-approvals'
import { Route as AuthSessionsIndexRouteImport } from './routes/_auth/sessions.index'
import { Route as AuthSessionsNewRouteImport } from './routes/_auth/sessions/new'
import { Route as AuthSessionsSessionIdRouteImport } from './routes/_auth/sessions/$sessionId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const Setup2faRoute = Setup2faRouteImport.update({
  id: '/setup-2fa',
  path: '/setup-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVitalsRoute = AuthVitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTrainBodyRoute = AuthTrainBodyRouteImport.update({
  id: '/train-body',
  path: '/train-body',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTestAiRoute = AuthTestAiRouteImport.update({
  id: '/test-ai',
  path: '/test-ai',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSymptomsRoute = AuthSymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPharmacistRoute = AuthPharmacistRouteImport.update({
  id: '/pharmacist',
  path: '/pharmacist',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNewsRoute = AuthNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMedicationsRoute = AuthMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => AuthRoute,
} as any)
const AuthKanbanRoute = AuthKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHealthHelpRoute = AuthHealthHelpRouteImport.update({
  id: '/health-help',
  path: '/health-help',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFriendChatRoute = AuthFriendChatRouteImport.update({
  id: '/friend-chat',
  path: '/friend-chat',
  getParentRoute: () => AuthRoute,
} as any)
const AuthErAlertsRoute = AuthErAlertsRouteImport.update({
  id: '/er-alerts',
  path: '/er-alerts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDrugInfoRoute = AuthDrugInfoRouteImport.update({
  id: '/drug-info',
  path: '/drug-info',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompanionRoute = AuthCompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAllergiesRoute = AuthAllergiesRouteImport.update({
  id: '/allergies',
  path: '/allergies',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAiAssistantRoute = AuthAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminPanelRoute = AuthAdminPanelRouteImport.update({
  id: '/admin-panel',
  path: '/admin-panel',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminBreachesRoute = AuthAdminBreachesRouteImport.update({
  id: '/admin-breaches',
  path: '/admin-breaches',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminApprovalsRoute = AuthAdminApprovalsRouteImport.update({
  id: '/admin-approvals',
  path: '/admin-approvals',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSessionsIndexRoute = AuthSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSessionsNewRoute = AuthSessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSessionsSessionIdRoute = AuthSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/setup-2fa': typeof Setup2faRoute
  '/sign-up': typeof SignUpRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin-approvals': typeof AuthAdminApprovalsRoute
  '/admin-breaches': typeof AuthAdminBreachesRoute
  '/admin-panel': typeof AuthAdminPanelRoute
  '/ai-assistant': typeof AuthAiAssistantRoute
  '/allergies': typeof AuthAllergiesRoute
  '/companion': typeof AuthCompanionRoute
  '/dashboard': typeof AuthDashboardRoute
  '/drug-info': typeof AuthDrugInfoRoute
  '/er-alerts': typeof AuthErAlertsRoute
  '/friend-chat': typeof AuthFriendChatRoute
  '/health-help': typeof AuthHealthHelpRoute
  '/kanban': typeof AuthKanbanRoute
  '/medications': typeof AuthMedicationsRoute
  '/news': typeof AuthNewsRoute
  '/pharmacist': typeof AuthPharmacistRoute
  '/profile': typeof AuthProfileRoute
  '/symptoms': typeof AuthSymptomsRoute
  '/test-ai': typeof AuthTestAiRoute
  '/train-body': typeof AuthTrainBodyRoute
  '/vitals': typeof AuthVitalsRoute
  '/sessions/$sessionId': typeof AuthSessionsSessionIdRoute
  '/sessions/new': typeof AuthSessionsNewRoute
  '/sessions/': typeof AuthSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/setup-2fa': typeof Setup2faRoute
  '/sign-up': typeof SignUpRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin-approvals': typeof AuthAdminApprovalsRoute
  '/admin-breaches': typeof AuthAdminBreachesRoute
  '/admin-panel': typeof AuthAdminPanelRoute
  '/ai-assistant': typeof AuthAiAssistantRoute
  '/allergies': typeof AuthAllergiesRoute
  '/companion': typeof AuthCompanionRoute
  '/dashboard': typeof AuthDashboardRoute
  '/drug-info': typeof AuthDrugInfoRoute
  '/er-alerts': typeof AuthErAlertsRoute
  '/friend-chat': typeof AuthFriendChatRoute
  '/health-help': typeof AuthHealthHelpRoute
  '/kanban': typeof AuthKanbanRoute
  '/medications': typeof AuthMedicationsRoute
  '/news': typeof AuthNewsRoute
  '/pharmacist': typeof AuthPharmacistRoute
  '/profile': typeof AuthProfileRoute
  '/symptoms': typeof AuthSymptomsRoute
  '/test-ai': typeof AuthTestAiRoute
  '/train-body': typeof AuthTrainBodyRoute
  '/vitals': typeof AuthVitalsRoute
  '/': typeof AuthIndexRoute
  '/sessions/$sessionId': typeof AuthSessionsSessionIdRoute
  '/sessions/new': typeof AuthSessionsNewRoute
  '/sessions': typeof AuthSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/setup-2fa': typeof Setup2faRoute
  '/sign-up': typeof SignUpRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_auth/admin-approvals': typeof AuthAdminApprovalsRoute
  '/_auth/admin-breaches': typeof AuthAdminBreachesRoute
  '/_auth/admin-panel': typeof AuthAdminPanelRoute
  '/_auth/ai-assistant': typeof AuthAiAssistantRoute
  '/_auth/allergies': typeof AuthAllergiesRoute
  '/_auth/companion': typeof AuthCompanionRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/drug-info': typeof AuthDrugInfoRoute
  '/_auth/er-alerts': typeof AuthErAlertsRoute
  '/_auth/friend-chat': typeof AuthFriendChatRoute
  '/_auth/health-help': typeof AuthHealthHelpRoute
  '/_auth/kanban': typeof AuthKanbanRoute
  '/_auth/medications': typeof AuthMedicationsRoute
  '/_auth/news': typeof AuthNewsRoute
  '/_auth/pharmacist': typeof AuthPharmacistRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/symptoms': typeof AuthSymptomsRoute
  '/_auth/test-ai': typeof AuthTestAiRoute
  '/_auth/train-body': typeof AuthTrainBodyRoute
  '/_auth/vitals': typeof AuthVitalsRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/sessions/$sessionId': typeof AuthSessionsSessionIdRoute
  '/_auth/sessions/new': typeof AuthSessionsNewRoute
  '/_auth/sessions/': typeof AuthSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pending-approval'
    | '/privacy-policy'
    | '/setup-2fa'
    | '/sign-up'
    | '/two-factor'
    | '/verify-email'
    | '/admin-approvals'
    | '/admin-breaches'
    | '/admin-panel'
    | '/ai-assistant'
    | '/allergies'
    | '/companion'
    | '/dashboard'
    | '/drug-info'
    | '/er-alerts'
    | '/friend-chat'
    | '/health-help'
    | '/kanban'
    | '/medications'
    | '/news'
    | '/pharmacist'
    | '/profile'
    | '/symptoms'
    | '/test-ai'
    | '/train-body'
    | '/vitals'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/pending-approval'
    | '/privacy-policy'
    | '/setup-2fa'
    | '/sign-up'
    | '/two-factor'
    | '/verify-email'
    | '/admin-approvals'
    | '/admin-breaches'
    | '/admin-panel'
    | '/ai-assistant'
    | '/allergies'
    | '/companion'
    | '/dashboard'
    | '/drug-info'
    | '/er-alerts'
    | '/friend-chat'
    | '/health-help'
    | '/kanban'
    | '/medications'
    | '/news'
    | '/pharmacist'
    | '/profile'
    | '/symptoms'
    | '/test-ai'
    | '/train-body'
    | '/vitals'
    | '/'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/sessions'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/pending-approval'
    | '/privacy-policy'
    | '/setup-2fa'
    | '/sign-up'
    | '/two-factor'
    | '/verify-email'
    | '/_auth/admin-approvals'
    | '/_auth/admin-breaches'
    | '/_auth/admin-panel'
    | '/_auth/ai-assistant'
    | '/_auth/allergies'
    | '/_auth/companion'
    | '/_auth/dashboard'
    | '/_auth/drug-info'
    | '/_auth/er-alerts'
    | '/_auth/friend-chat'
    | '/_auth/health-help'
    | '/_auth/kanban'
    | '/_auth/medications'
    | '/_auth/news'
    | '/_auth/pharmacist'
    | '/_auth/profile'
    | '/_auth/symptoms'
    | '/_auth/test-ai'
    | '/_auth/train-body'
    | '/_auth/vitals'
    | '/_auth/'
    | '/_auth/sessions/$sessionId'
    | '/_auth/sessions/new'
    | '/_auth/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  Setup2faRoute: typeof Setup2faRoute
  SignUpRoute: typeof SignUpRoute
  TwoFactorRoute: typeof TwoFactorRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-2fa': {
      id: '/setup-2fa'
      path: '/setup-2fa'
      fullPath: '/setup-2fa'
      preLoaderRoute: typeof Setup2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/vitals': {
      id: '/_auth/vitals'
      path: '/vitals'
      fullPath: '/vitals'
      preLoaderRoute: typeof AuthVitalsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/train-body': {
      id: '/_auth/train-body'
      path: '/train-body'
      fullPath: '/train-body'
      preLoaderRoute: typeof AuthTrainBodyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/test-ai': {
      id: '/_auth/test-ai'
      path: '/test-ai'
      fullPath: '/test-ai'
      preLoaderRoute: typeof AuthTestAiRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/symptoms': {
      id: '/_auth/symptoms'
      path: '/symptoms'
      fullPath: '/symptoms'
      preLoaderRoute: typeof AuthSymptomsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pharmacist': {
      id: '/_auth/pharmacist'
      path: '/pharmacist'
      fullPath: '/pharmacist'
      preLoaderRoute: typeof AuthPharmacistRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/news': {
      id: '/_auth/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthNewsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/medications': {
      id: '/_auth/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof AuthMedicationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/kanban': {
      id: '/_auth/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthKanbanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/health-help': {
      id: '/_auth/health-help'
      path: '/health-help'
      fullPath: '/health-help'
      preLoaderRoute: typeof AuthHealthHelpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/friend-chat': {
      id: '/_auth/friend-chat'
      path: '/friend-chat'
      fullPath: '/friend-chat'
      preLoaderRoute: typeof AuthFriendChatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/er-alerts': {
      id: '/_auth/er-alerts'
      path: '/er-alerts'
      fullPath: '/er-alerts'
      preLoaderRoute: typeof AuthErAlertsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/drug-info': {
      id: '/_auth/drug-info'
      path: '/drug-info'
      fullPath: '/drug-info'
      preLoaderRoute: typeof AuthDrugInfoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/companion': {
      id: '/_auth/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof AuthCompanionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/allergies': {
      id: '/_auth/allergies'
      path: '/allergies'
      fullPath: '/allergies'
      preLoaderRoute: typeof AuthAllergiesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ai-assistant': {
      id: '/_auth/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthAiAssistantRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin-panel': {
      id: '/_auth/admin-panel'
      path: '/admin-panel'
      fullPath: '/admin-panel'
      preLoaderRoute: typeof AuthAdminPanelRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin-breaches': {
      id: '/_auth/admin-breaches'
      path: '/admin-breaches'
      fullPath: '/admin-breaches'
      preLoaderRoute: typeof AuthAdminBreachesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin-approvals': {
      id: '/_auth/admin-approvals'
      path: '/admin-approvals'
      fullPath: '/admin-approvals'
      preLoaderRoute: typeof AuthAdminApprovalsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sessions/': {
      id: '/_auth/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthSessionsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sessions/new': {
      id: '/_auth/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof AuthSessionsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sessions/$sessionId': {
      id: '/_auth/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthSessionsSessionIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAdminApprovalsRoute: typeof AuthAdminApprovalsRoute
  AuthAdminBreachesRoute: typeof AuthAdminBreachesRoute
  AuthAdminPanelRoute: typeof AuthAdminPanelRoute
  AuthAiAssistantRoute: typeof AuthAiAssistantRoute
  AuthAllergiesRoute: typeof AuthAllergiesRoute
  AuthCompanionRoute: typeof AuthCompanionRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDrugInfoRoute: typeof AuthDrugInfoRoute
  AuthErAlertsRoute: typeof AuthErAlertsRoute
  AuthFriendChatRoute: typeof AuthFriendChatRoute
  AuthHealthHelpRoute: typeof AuthHealthHelpRoute
  AuthKanbanRoute: typeof AuthKanbanRoute
  AuthMedicationsRoute: typeof AuthMedicationsRoute
  AuthNewsRoute: typeof AuthNewsRoute
  AuthPharmacistRoute: typeof AuthPharmacistRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthSymptomsRoute: typeof AuthSymptomsRoute
  AuthTestAiRoute: typeof AuthTestAiRoute
  AuthTrainBodyRoute: typeof AuthTrainBodyRoute
  AuthVitalsRoute: typeof AuthVitalsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthSessionsSessionIdRoute: typeof AuthSessionsSessionIdRoute
  AuthSessionsNewRoute: typeof AuthSessionsNewRoute
  AuthSessionsIndexRoute: typeof AuthSessionsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminApprovalsRoute: AuthAdminApprovalsRoute,
  AuthAdminBreachesRoute: AuthAdminBreachesRoute,
  AuthAdminPanelRoute: AuthAdminPanelRoute,
  AuthAiAssistantRoute: AuthAiAssistantRoute,
  AuthAllergiesRoute: AuthAllergiesRoute,
  AuthCompanionRoute: AuthCompanionRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDrugInfoRoute: AuthDrugInfoRoute,
  AuthErAlertsRoute: AuthErAlertsRoute,
  AuthFriendChatRoute: AuthFriendChatRoute,
  AuthHealthHelpRoute: AuthHealthHelpRoute,
  AuthKanbanRoute: AuthKanbanRoute,
  AuthMedicationsRoute: AuthMedicationsRoute,
  AuthNewsRoute: AuthNewsRoute,
  AuthPharmacistRoute: AuthPharmacistRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthSymptomsRoute: AuthSymptomsRoute,
  AuthTestAiRoute: AuthTestAiRoute,
  AuthTrainBodyRoute: AuthTrainBodyRoute,
  AuthVitalsRoute: AuthVitalsRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthSessionsSessionIdRoute: AuthSessionsSessionIdRoute,
  AuthSessionsNewRoute: AuthSessionsNewRoute,
  AuthSessionsIndexRoute: AuthSessionsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  Setup2faRoute: Setup2faRoute,
  SignUpRoute: SignUpRoute,
  TwoFactorRoute: TwoFactorRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
