import { db as _db, task } from "@sanotalk/db";
import { resend } from "./resend";
import { escapeHtml, sanitizeSubject } from "./escape-html";

type Db = typeof _db;

const TASK_TITLE_BY_LANG: Record<string, (patientName: string) => string> = {
  en: (n) => `Review summary for patient ${n}`,
  fr: (n) => `Réviser le résumé du patient ${n}`,
  es: (n) => `Revisar el resumen del paciente ${n}`,
  zh: (n) => `查看患者 ${n} 的摘要`,
  ar: (n) => `مراجعة ملخص المريض ${n}`,
  hi: (n) => `मरीज़ ${n} का सारांश देखें`,
};

function renderBody(senderName: string, summaryUrl: string): string {
  return `
        <div style="font-family:sans-serif;max-width:600px;margin:0 auto">
          <h2 style="color:#1a1a1a">Consultation Summary Available</h2>
          <p style="color:#555">A new consultation summary from <strong>${escapeHtml(senderName)}</strong> is ready to view.</p>
          <hr style="border:none;border-top:1px solid #eee;margin:16px 0"/>
          <p style="color:#333">For security and privacy reasons, medical details are not included in this email.</p>
          <p>
            <a href="${escapeHtml(summaryUrl)}" style="display:inline-block;padding:12px 24px;background:#2563eb;color:#fff;text-decoration:none;border-radius:6px;font-weight:600">
              View Summary
            </a>
          </p>
          <p style="color:#999;font-size:12px;margin-top:24px">
            You must be logged in to SanoTalk to view the summary.
            If you did not expect this notification, you can ignore it.
          </p>
          <hr style="border:none;border-top:1px solid #eee;margin:16px 0"/>
          <p style="color:#999;font-size:11px">Sent from SanoTalk. This summary was generated by AI and is for informational purposes only.</p>
        </div>
      `;
}

/**
 * Emails the linked professional that a consultation summary is available and
 * creates a `summary_review` task for them. Shared by the tRPC `sendSummary`
 * procedure (explicit patient-initiated send) and the server-side
 * `autoSendSummaryToLinkedProfessional` hook (auto-send on generation).
 */
export async function sendSummaryEmail(params: {
  db: Db;
  recipientId: string;
  recipientEmail: string;
  senderName: string;
  sessionId: string;
  sessionLanguage: string;
}) {
  const { db, recipientId, recipientEmail, senderName, sessionId, sessionLanguage } = params;
  const from = process.env.EMAIL_FROM ?? "onboarding@resend.dev";
  const appUrl = process.env.APP_URL ?? "";
  const summaryUrl = `${appUrl}/sessions/${sessionId}?tab=summary`;

  const titleFactory = TASK_TITLE_BY_LANG[sessionLanguage] ?? TASK_TITLE_BY_LANG["en"]!;
  const taskTitle = titleFactory(senderName);

  await resend.emails.send({
    from,
    to: recipientEmail,
    subject: `SanoTalk — Consultation summary available for ${sanitizeSubject(senderName)}`,
    html: renderBody(senderName, summaryUrl),
  });

  await db.insert(task).values({
    title: taskTitle,
    description: summaryUrl,
    status: "assigned",
    assignedUserId: recipientId,
    taskType: "summary_review",
  });
}
